### ISSUE TITLE
Change timecode of exported CSV blendshapes

### ISSUE THREAD

**Issue by AndersenJari99** [OlineRanum/GLEX_Controller#16]
Can we, and should we (for this project) change the timecode of the exported csv blendshapes from the IPhone to the ones used in Vicon and HE?
This would enable us to sync the recordings better.

**Comment by rem0g** [comment]
We can try NTP timecode set at time.apple.com as that's the best way at livelink, so hopefully that would be possible on vicon/UE.

**Comment by rem0g** [comment]
duplicate
