### ISSUE TITLE
Timecode in CSV Live Link Face

### ISSUE THREAD

**Issue by AndersenJari99** [OlineRanum/GLEX_Controller#19]
We need the same TimeCode in the csv of the blendshapes. Currently the IPhone uses its own timecode.
The Live Link Face application on the IPhone does have a Timecode section.
How are we going to use the same source for the Vicon system as well?

**Comment by rem0g** [comment]
Vicon / HE use own timecode and for this project we dont need to use livelink face for preciese matching. Issue still unssolved.
