### ISSUE TITLE
Directory check function

### ISSUE THREAD

**Issue by AndersenJari99** [OlineRanum/GLEX_Controller#20]
We should add a directory check function. When we give a file name, we want to be sure that this file isn't already in use. Shogun already signals that we can't use the same file names, but we should add this to the controller or another part of the model so the other systems don't use the same file name either.

**Comment by AndersenJari99** [comment]
- [ ] Change print for callback to GOP

**Comment by rem0g** [comment]
Done with the GOP, Shogun makes new flies but we have to check what HE does .
