### ISSUE TITLE
Replay avatar in UE5 instead of playcanvas

### ISSUE THREAD

**Issue by AndersenJari99** [OlineRanum/GLEX_Controller#23]
We would like the replay of the avatar in UE5 instead of playcanvas. Playcanvas loading the avatar simply takes too long, we can win more time by replaying through UE.

**Comment by rem0g** [comment]
https://www.youtube.com/watch?v=35RJqR4Z5BI

**Comment by rem0g** [comment]
https://blueprintue.com/blueprint/j04pxm3z/
